- name: Remove old Docker repository file (avoid conflicts)
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent
  become: yes

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  become: yes

- name: Download Docker GPG key (Ubuntu)
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.gpg
    mode: "0644"
  when: ansible_facts['distribution'] == "Ubuntu"
  become: yes

- name: Download Docker GPG key (Debian)
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.gpg
    mode: "0644"
  when: ansible_facts['distribution'] == "Debian"
  become: yes

- name: Add Docker repository (Ubuntu)
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  when: ansible_facts['distribution'] == "Ubuntu"
  become: yes

- name: Add Docker repository (Debian)
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  when: ansible_facts['distribution'] == "Debian"
  become: yes