##### VTEPS LO#####

r1_lo0: "1.1.1.1/32"
r2_lo0: "2.2.2.2/32"
r3_lo0: "3.3.3.3/32"
r4_lo0: "4.4.4.4/32"


##### AREAS ##### VNI 10 ###

area1: "192.168.10."
area1_submask: "/24"


##### HOSTS # ### VNI 10 ####

VNI_10: "10"

h1_ip: "{{ area1 }}100"

h2_ip: "{{ area1 }}101"

h3_ip: "{{ area1 }}102"

