- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install prerequisites
  apt:
    name:
      - ubridge
    state: present
  become: yes


- block:
    - name: Add GNS3 PPA
      apt_repository:
        repo: ppa:gns3/ppa
        state: present
        update_cache: yes
      become: yes

    - name: Install GNS3
      apt:
        name:
          - gns3-gui
          - gns3-server
        state: present
        update_cache: yes
      become: yes

  when: ansible_facts['distribution'] == "Ubuntu"


- block:
  - name: Install pip3 and PyQt5 (Debian only)
    apt:
      name:
        - python3-pip
        - python3-pyqt5
        - python3-pyqt5.qtsvg
        - python3-pyqt5.qtwebsockets
      state: present
    become: yes

  - name: Install GNS3 server via pip3 (Debian only)
    pip:
      name: gns3-server
      executable: pip3
      extra_args: "--break-system-packages"
      state: present
    become: yes
  when: ansible_facts['distribution'] == "Debian"


- name: Add user to groups
  user:
    name: "{{ ansible_user }}"
    groups:
      - ubridge
      - wireshark
      - kvm
    append: yes
  become: yes
  ignore_errors: yes

- name: Clean apt cache
  apt:
    autoclean: yes
    autoremove: yes
  become: yes